name: Laravel CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        working-directory: ./server
        run: composer install --no-scripts --prefer-dist --optimize-autoloader

      - name: Run tests
        working-directory: ./server
        run: vendor/bin/phpunit --exclude-group google

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      ROOT_DIR: /var/www/pigment
      APP_DIR: /var/www/pigment/api
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RELEASE_DIR: /var/www/pigment/api/releases/${{ github.sha }}

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export ROOT_DIR=$ROOT_DIR
            export RELEASE_DIR=$RELEASE_DIR
            cd $ROOT_DIR
            echo "$RELEASE_DIR"
            git clone --depth 1 https://github.com/colinxr/pigment.git repo
            cd repo
            git reset --hard HEAD
            cp /var/www/pigment/.env server/.env
            if [ -d "/var/www/pigment/api/current/storage" ]; then
                cp -r /var/www/pigment/api/current/storage "$RELEASE_DIR/storage" 
            fi
            mkdir -p $RELEASE_DIR
            cp -rpa server/* $RELEASE_DIR
            cd $ROOT_DIR && rm -rf repo

      - name: Run Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export ROOT_DIR=$ROOT_DIR
            export RELEASE_DIR=$RELEASE_DIR
            echo $RELEASE_DIR
            cd $RELEASE_DIR/server 
            pwd
            composer install --no-dev
            php artisan migrate --force
            php artisan cache:clear
            php artisan optimize

      - name: Symlink Release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export RELEASE_DIR=$RELEASE_DIR
            export APP_DIR=$RELEASE_DIR
            rm -rf $APP_DIR/current
            ln -s $RELEASE_DIR/server /var/www/pigment/api/current
