name: Laravel CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        working-directory: ./server
        run: composer install --no-scripts --prefer-dist --optimize-autoloader

      - name: Run tests
        working-directory: ./server
        run: vendor/bin/phpunit --exclude-group google

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_DIR: /var/www/pigment/api
      RELEASE_DIR: /var/www/pigment/api/releases/$(date +'%Y%m%d%H%M')
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Deploy to server
        env:
          REPO_DIR: /var/www/pigment/repo
          RELEASE_DIR: /var/www/pigment/api/releases/$(date +'%Y%m%d%H%M')
          APP_DIR: /var/www/pigment/api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf "$REPO_DIR"
            git clone --depth 1 https://github.com/colinxr/pigment.git "$REPO_DIR"
            cd repo
            git reset --hard HEAD
            cp /var/www/pigment/.env "$REPO_DIR/server"
            if [ -d "/var/www/pigment/api/current/storage" ]; then
                cp -r /var/www/pigment/api/current/storage "$RELEASE_DIR/storage" 
            fi
            cp "$REPO_DIR/server" "$RELEASE_DIR"

      - name: Run Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $RELEASE_DIR 
            composer install --no-dev
            php artisan migrate --force
            php artisan cache:clear
            php artisan optimize

      - name: Symlink Release
        env:
          RELEASE_DIR: /var/www/pigment/api/releases/$(date +'%Y%m%d%H%M')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/pigment/api/current
            ln -s $RELEASE_DIR /var/www/pigment/api/current
