name: Nuxt CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/web.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Build App
        working-directory: ./web
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_DIR: /var/www/pigment/api
      RELEASE_DIR: /var/www/pigment/api/releases/$(date +'%Y%m%d%H%M')
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Deploy to Server
        working-directory: ./web
        run: |
          scp -r .output/server/* $SERVER_USER@$SERVER_HOST:/var/www/pigment/web/releases/$(date +'%Y%m%d%H%M')
          ssh -i $SERVER_PRIVATE_KEY $SERVER_USER@$SERVER_HOST "
            rm -rf /var/www/pigment/web/active
            ln -s /var/www/pigment/web/releases/$(date +'%Y%m%d%H%M') /var/www/pigment/web/active
            pm2 reload ecosystem.config.js --env production
          "
