name: Nuxt CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "/web/**"
      - ".github/workflows/web.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH__PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          scp -r .output/server/* {{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/pigment/web/releases/$(date +'%Y%m%d%H%M')
          ssh {{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            rm -rf /var/www/pigment/web/active
            ln -s /var/www/pigment/web/releases/$(date +'%Y%m%d%H%M') /var/www/pigment/web/active
            pm2 reload ecosystem.config.js --env production
          "
